version: "3.2"

volumes:
  ftsdata:

services:
  # fts:
  #   build:
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "8080:8080"
  #     - "8087:8087"
  #     - "9000:9000"
  #     - "19023:19023"
  #   volumes:
  #     - ftsdata:/opt/FTSData
  #   environment:
  #     - FTS_DP_ADDRESS="$${curl ifconfig.me}"

  pub-fts:
    # docker run -d -p 8080:8080/tcp -p 8087:8087/tcp -e FTS_CONNECTION_MESSAGE="Server Connection Message" -e FTS_SAVE_COT_TO_DB="True" -v fts_data:/host/system/folder --name fts --restart unless-stopped freetakteam/freetakserver:1.1.2
    image: freetakteam/freetakserver:1.1.2
    ports:
      - "8080:8080"
      - "8087:8087"
    environment:
      - FTS_CONNECTION_MESSAGE="Server Connection Message"
      - FTS_SAVE_COT_TO_DB="True"
    volumes:
      - ftsdata:/host/system/folder

